### ISSUE TITLE
Log.CloseAndFlush with Async sink causes System.OperationCanceledException on .NET 8.0

### ISSUE THREAD

**Issue by mayka-mack** [serilog/serilog-sinks-async#91]
I'm getting an error when using the asynchronous wrapper and calling `Log.CloseAndFlush()` on .NET 8.0 if there's no longer data to flush. I've recreated with both the console and file sinks. I'm using .NET 8.0 with the latest stable version of `Serilog` (3.1.1) and `Serilog.Sinks.Async` (1.5.0). The issue does **not** occur when using .NET 7.0 or earlier. This may well be an issue with Serilog or .NET 8.0 rather than the async wrapper, but I figured I would start here. Is there a way to track down what may be the root cause of this?

The error is specifically raised on the `_worker.Wait();` line within the `Dispose()` method of the `BackgroundWorkerSink` class. And oddly enough, if I put a breakpoint within the `Pump()` method in `BackgroundWorkerSink` on `_wrappedSink.Emit(next);` and pause for a moment before issuing the command, I'm then *not* getting the error.

The below adds in a pause before flushing, which reproduces the error reliably.
```
Log.Logger = new LoggerConfiguration().WriteTo.Async(a => a.Console()).CreateLogger();
Log.Information("Logging to console");
Thread.Sleep(1000);
Log.CloseAndFlush();
Console.ReadKey();
```
### Error Message:
```
System.OperationCanceledException
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs:line 390
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
```

**Comment by mayka-mack** [comment]
Digging into this a bit more, the error is raised within the `BackgroundWorkerSink` class, on the `_worker.Wait();` line within the `Dispose()` method.

**Comment by mayka-mack** [comment]
I have replicated this without the async sink in the below code, so this may be something with the .NET 8.0 runtime itself. I will try raising an issue on their GitHub. Leaving this open so I can report back if it's truly an issue or by design.
```
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

BlockingCollection<string> queue = new();
Task task = Task.Run(() =>
{
    foreach (string next in queue.GetConsumingEnumerable()) { }
});

Thread.Sleep(1000);
queue.CompleteAdding();
task.Wait();
```

**Comment by mayka-mack** [comment]
It looks like this was an issue with the Visual Studio debugger incorrectly breaking on non-user code for first-chance exceptions. I cannot repro after upgrading to VS 17.9, so I am closing this issue now that I can circle back with a "resolution".
